<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is a "digital artifact" that contains the grammar specified by
ISO/IEC 39075.

The grammar is specified using the XML vocabulary used to specify
ISO/IEC 39075 itself. This file contains an XML DTD that specifies
that XML vocabulary. 

This grammar may be used by implementers of GQL-implementations
when generating parsers for the GQL language.
  -->
 
<!DOCTYPE grammar [

<!-- Element definitions 
-->

<!-- A grammar consists of a set of BNF definitions. 
-->
<!ELEMENT grammar ( BNFdef* )>


<!-- A BNFdef element defines a syntactic component.
-->
<!ELEMENT BNFdef (rhs)>
<!-- The attributes of BNFdef are:
      * name is the name of the component.
      * predicative is an indication of whether it is a production rule that defines a syntactic
        element not only in terms of the production rule itself but also in terms of further
        restrictions imposed on it by additional Syntax Rules such that the production rule cannot
        sufficiently distinguish the syntactic element from the syntactic elements defined by
        another production rule in an alternative between those two production rules without
        considering those restrictions.
-->
<!ATTLIST BNFdef
  name CDATA #REQUIRED
  predicative ( yes | no ) #IMPLIED 
>


<!-- The rhs element specifies the production for the syntactic component being defined.
-->
<!ELEMENT rhs ( seeTheRules
              | ( ( alt )+, seeTheRules? )
              | ( ( opt 
                  | group 
                  | terminalsymbol 
                  | kw 
                  | repeat 
                  | BNF 
                  ), seeTheRules? )+
              )>


<!-- An alt element specifies one alternative production for the syntactic component being defined.
-->
<!ELEMENT alt (#PCDATA | allAltsFrom | opt | group | terminalsymbol | kw   
                | bold | repeat | BNF )* >


<!-- A BNF element references a BNFdef
-->
<!ELEMENT BNF EMPTY>
<!-- The attributes of BNF are:
      * name is the name of the BNFdef.
      * part is the number of the part in which the BNFdef is defined if not this document.
      * standard is the number of the standard in which the BNFdef is defined if not this standard.
-->
<!ATTLIST BNF
  name CDATA #REQUIRED
  part CDATA #IMPLIED
  standard CDATA #IMPLIED
>


<!-- An allAltsFrom element represents "!! All alternatives from ..." 
     where ... identifies the other part.
-->
<!ELEMENT allAltsFrom EMPTY>
<!-- The attributes of allAltsFrom are:
      * part is the number of the part in which the BNFdef is originally defined.
      * standard is the number of the standard in which the BNFdef is originally defined if not
        this standard.
-->
<!ATTLIST allAltsFrom
  part CDATA #REQUIRED
  standard CDATA #IMPLIED
>


<!-- An opt element defines an optional component of a production.
     This is shown by enclosure between [ and ].
-->
<!ELEMENT opt (#PCDATA | alt | opt | group| terminalsymbol | kw  
                 | repeat | BNF )*>


<!-- A group element groups two or more components of a production as an inseparable component.
     This is shown by enclosure between { and }.
-->
<!ELEMENT group (#PCDATA | alt | opt | group| terminalsymbol | kw   
                 | repeat | BNF )*>


<!-- A repeat indicates possible repetition of a component.
     This is shown as three dots...
-->
<!ELEMENT repeat EMPTY>


<!-- A terminalsymbol element defines literal characters in the production.
-->
<!ELEMENT terminalsymbol (#PCDATA)*>
<!-- The attribute of terminalsymbol is:
     * unicode defines the code point(s). 
           These are defined as the 4, 5 or 6 hex character(s) separated by commas.
           For example, unicode="0026" or unicode="007E,005B"
-->
<!ATTLIST terminalsymbol
  unicode CDATA #IMPLIED
>

<!-- A kw element defines its contents as a normal keyword.
-->
<!ELEMENT kw (#PCDATA)>


 
<!-- A bold indicates the use of a bold-faced type font.
-->
<!ELEMENT bold (#PCDATA)>


<!-- A seeTheRules element represents the sequence "!! See the Syntax Rules".
-->
<!ELEMENT seeTheRules EMPTY>
]>

<grammar>
   <BNFdef name="GQL-program" predicative="no">
      <rhs>
         <alt>
            <BNF name="program activity"/>
            <opt>
               <BNF name="session close command"/>
            </opt>
         </alt>
         <alt>
            <BNF name="session close command"/>
         </alt>
      </rhs>
   </BNFdef>
   <BNFdef name="program activity" predicative="no">
      <rhs>
         <alt>
            <BNF name="session activity"/>
         </alt>
         <alt>
            <BNF name="transaction activity"/>
         </alt>
      </rhs>
   </BNFdef>
   <BNFdef name="session activity" predicative="no">
      <rhs>
         <alt>
            <BNF name="session reset command"/>
            <repeat/>
         </alt>
         <alt>
            <BNF name="session set command"/>
            <repeat/>
            <opt>
               <BNF name="session reset command"/>
               <repeat/>
            </opt>
         </alt>
      </rhs>
   </BNFdef>
   <BNFdef name="transaction activity" predicative="no">
      <rhs>
         <alt>
            <BNF name="start transaction command"/>
            <opt>
               <BNF name="procedure specification"/>
               <opt>
                  <BNF name="end transaction command"/>
               </opt>
            </opt>
         </alt>
         <alt>
            <BNF name="procedure specification"/>
            <opt>
               <BNF name="end transaction command"/>
            </opt>
         </alt>
         <alt>
            <BNF name="end transaction command"/>
         </alt>
      </rhs>
   </BNFdef>
   <BNFdef name="end transaction command" predicative="no">
      <rhs>
         <alt>
            <BNF name="rollback command"/>
         </alt>
         <alt>
            <BNF name="commit command"/>
         </alt>
      </rhs>
   </BNFdef>
   <BNFdef name="session set command" predicative="no">
      <rhs>
         <kw>SESSION</kw>
         <kw>SET</kw>
         <group>
            <alt>
               <BNF name="session set schema clause"/>
            </alt>
            <alt>
               <BNF name="session set graph clause"/>
            </alt>
            <alt>
               <BNF name="session set time zone clause"/>
            </alt>
            <alt>
               <BNF name="session set parameter clause"/>
            </alt>
            <alt>
               <BNF name="session set list behavior clause"/>
            </alt>
         </group>
      </rhs>
   </BNFdef>
   <BNFdef name="session set schema clause" predicative="no">
      <rhs>
         <kw>SCHEMA</kw>
         <BNF name="schema reference"/>
      </rhs>
   </BNFdef>
   <BNFdef name="session set graph clause" predicative="no">
      <rhs>
         <opt>
            <kw>PROPERTY</kw>
         </opt>
         <kw>GRAPH</kw>
         <BNF name="graph expression"/>
      </rhs>
   </BNFdef>
   <BNFdef name="session set time zone clause" predicative="no">
      <rhs>
         <kw>TIME</kw>
         <kw>ZONE</kw>
         <BNF name="set time zone value"/>
      </rhs>
   </BNFdef>
   <BNFdef name="set time zone value" predicative="no">
      <rhs>
         <BNF name="time zone string"/>
      </rhs>
   </BNFdef>
   <BNFdef name="session set parameter clause" predicative="no">
      <rhs>
         <alt>
            <BNF name="session set graph parameter clause"/>
         </alt>
         <alt>
            <BNF name="session set binding table parameter clause"/>
         </alt>
         <alt>
            <BNF name="session set value parameter clause"/>
         </alt>
      </rhs>
   </BNFdef>
   <BNFdef name="session set graph parameter clause" predicative="no">
      <rhs>
         <opt>
            <kw>PROPERTY</kw>
         </opt>
         <kw>GRAPH</kw>
         <BNF name="session set parameter name"/>
         <BNF name="opt typed graph initializer"/>
      </rhs>
   </BNFdef>
   <BNFdef name="session set binding table parameter clause" predicative="no">
      <rhs>
         <opt>
            <kw>BINDING</kw>
         </opt>
         <kw>TABLE</kw>
         <BNF name="session set parameter name"/>
         <BNF name="opt typed binding table initializer"/>
      </rhs>
   </BNFdef>
   <BNFdef name="session set value parameter clause" predicative="no">
      <rhs>
         <kw>VALUE</kw>
         <BNF name="session set parameter name"/>
         <BNF name="opt typed value initializer"/>
      </rhs>
   </BNFdef>
   <BNFdef name="session set parameter name" predicative="no">
      <rhs>
         <opt>
            <kw>IF</kw>
            <kw>NOT</kw>
            <kw>EXISTS</kw>
         </opt>
         <BNF name="session parameter specification"/>
      </rhs>
   </BNFdef>
   <BNFdef name="session set list behavior clause" predicative="no">
      <rhs>
         <alt>
            <BNF name="list value type name synonym"/>
            <kw>BEHAVIOR</kw>
            <BNF name="list behavior"/>
         </alt>
         <alt>
            <BNF name="list value type name synonym"/>
            <kw>BEHAVIOR</kw>
            <BNF name="left paren"/>
            <BNF name="list behavior"/>
            <opt>
               <group>
                  <BNF name="comma"/>
                  <BNF name="list behavior"/>
               </group>
               <repeat/>
            </opt>
            <BNF name="right paren"/>
         </alt>
      </rhs>
   </BNFdef>
   <BNFdef name="list behavior" predicative="no">
      <rhs>
         <alt>
            <kw>INDEX</kw>
            <BNF name="offset or ordinal"/>
         </alt>
         <alt>
            <kw>NEGATIVE</kw>
            <kw>INDEX</kw>
            <BNF name="from end or out of range"/>
         </alt>
         <alt>
            <kw>OUT</kw>
            <kw>OF</kw>
            <kw>RANGE</kw>
            <BNF name="null or error"/>
         </alt>
      </rhs>
   </BNFdef>
   <BNFdef name="offset or ordinal" predicative="no">
      <rhs>
         <alt>
            <kw>OFFSET</kw>
         </alt>
         <alt>
            <kw>ORDINAL</kw>
         </alt>
      </rhs>
   </BNFdef>
   <BNFdef name="from end or out of range" predicative="no">
      <rhs>
         <alt>
            <kw>FROM</kw>
            <kw>END</kw>
         </alt>
         <alt>
            <kw>OUT</kw>
            <kw>OF</kw>
            <kw>RANGE</kw>
         </alt>
      </rhs>
   </BNFdef>
   <BNFdef name="null or error" predicative="no">
      <rhs>
         <alt>
            <kw>NULL</kw>
         </alt>
         <alt>
            <kw>ERROR</kw>
         </alt>
      </rhs>
   </BNFdef>
   <BNFdef name="session reset command" predicative="no">
      <rhs>
         <kw>SESSION</kw>
         <kw>RESET</kw>
         <opt>
            <BNF name="session reset arguments"/>
         </opt>
      </rhs>
   </BNFdef>
   <BNFdef name="session reset arguments" predicative="no">
      <rhs>
         <alt>
            <opt>
               <kw>ALL</kw>
            </opt>
            <group>
               <alt>
                  <kw>PARAMETERS</kw>
               </alt>
               <alt>
                  <kw>CHARACTERISTICS</kw>
               </alt>
            </group>
         </alt>
         <alt>
            <kw>SCHEMA</kw>
         </alt>
         <alt>
            <opt>
               <kw>PROPERTY</kw>
            </opt>
            <kw>GRAPH</kw>
         </alt>
         <alt>
            <kw>TIME</kw>
            <kw>ZONE</kw>
         </alt>
         <alt>
            <opt>
               <kw>PARAMETER</kw>
            </opt>
            <BNF name="session parameter specification"/>
         </alt>
         <alt>
            <BNF name="list value type name synonym"/>
            <kw>BEHAVIOR</kw>
         </alt>
      </rhs>
   </BNFdef>
   <BNFdef name="session close command" predicative="no">
      <rhs>
         <kw>SESSION</kw>
         <kw>CLOSE</kw>
      </rhs>
   </BNFdef>
   <BNFdef name="session parameter specification" predicative="no">
      <rhs>
         <BNF name="general parameter reference"/>
      </rhs>
   </BNFdef>
   <BNFdef name="start transaction command" predicative="no">
      <rhs>
         <kw>START</kw>
         <kw>TRANSACTION</kw>
         <opt>
            <BNF name="transaction characteristics"/>
         </opt>
      </rhs>
   </BNFdef>
   <BNFdef name="transaction characteristics" predicative="no">
      <rhs>
         <BNF name="transaction mode"/>
         <opt>
            <group>
               <BNF name="comma"/>
               <BNF name="transaction mode"/>
            </group>
            <repeat/>
         </opt>
      </rhs>
   </BNFdef>
   <BNFdef name="transaction mode" predicative="no">
      <rhs>
         <alt>
            <BNF name="transaction access mode"/>
         </alt>
         <alt>
            <BNF name="implementation-defined access mode"/>
         </alt>
      </rhs>
   </BNFdef>
   <BNFdef name="transaction access mode" predicative="no">
      <rhs>
         <alt>
            <kw>READ</kw>
            <kw>ONLY</kw>
         </alt>
         <alt>
            <kw>READ</kw>
            <kw>WRITE</kw>
         </alt>
      </rhs>
   </BNFdef>
   <BNFdef name="implementation-defined access mode" predicative="no">
      <rhs>
         <seeTheRules/>
      </rhs>
   </BNFdef>
   <BNFdef name="rollback command" predicative="no">
      <rhs>
         <kw>ROLLBACK</kw>
      </rhs>
   </BNFdef>
   <BNFdef name="commit command" predicative="no">
      <rhs>
         <kw>COMMIT</kw>
      </rhs>
   </BNFdef>
   <BNFdef name="nested procedure specification" predicative="no">
      <rhs>
         <BNF name="left brace"/>
         <BNF name="procedure specification"/>
         <BNF name="right brace"/>
      </rhs>
   </BNFdef>
   <BNFdef name="procedure specification" predicative="no">
      <rhs>
         <alt>
            <BNF name="catalog-modifying procedure specification"/>
         </alt>
         <alt>
            <BNF name="data-modifying procedure specification"/>
         </alt>
         <alt>
            <BNF name="query specification"/>
         </alt>
      </rhs>
   </BNFdef>
   <BNFdef name="catalog-modifying procedure specification" predicative="no">
      <rhs>
         <BNF name="procedure body"/>
      </rhs>
   </BNFdef>
   <BNFdef name="nested data-modifying procedure specification" predicative="no">
      <rhs>
         <BNF name="left brace"/>
         <BNF name="data-modifying procedure specification"/>
         <BNF name="right brace"/>
      </rhs>
   </BNFdef>
   <BNFdef name="data-modifying procedure specification" predicative="no">
      <rhs>
         <BNF name="procedure body"/>
      </rhs>
   </BNFdef>
   <BNFdef name="nested query specification" predicative="no">
      <rhs>
         <BNF name="left brace"/>
         <BNF name="query specification"/>
         <BNF name="right brace"/>
      </rhs>
   </BNFdef>
   <BNFdef name="query specification" predicative="no">
      <rhs>
         <BNF name="procedure body"/>
      </rhs>
   </BNFdef>
   <BNFdef name="procedure body" predicative="no">
      <rhs>
         <opt>
            <BNF name="at schema clause"/>
         </opt>
         <opt>
            <BNF name="binding variable definition block"/>
         </opt>
         <BNF name="statement block"/>
      </rhs>
   </BNFdef>
   <BNFdef name="binding variable definition block" predicative="no">
      <rhs>
         <BNF name="binding variable definition"/>
         <repeat/>
      </rhs>
   </BNFdef>
   <BNFdef name="binding variable definition" predicative="no">
      <rhs>
         <alt>
            <BNF name="graph variable definition"/>
         </alt>
         <alt>
            <BNF name="binding table variable definition"/>
         </alt>
         <alt>
            <BNF name="value variable definition"/>
         </alt>
      </rhs>
   </BNFdef>
   <BNFdef name="statement block" predicative="no">
      <rhs>
         <BNF name="statement"/>
         <opt>
            <BNF name="next statement"/>
            <repeat/>
         </opt>
      </rhs>
   </BNFdef>
   <BNFdef name="statement" predicative="no">
      <rhs>
         <alt>
            <BNF name="linear catalog-modifying statement"/>
         </alt>
         <alt>
            <BNF name="linear data-modifying statement"/>
         </alt>
         <alt>
            <BNF name="composite query statement"/>
         </alt>
         <alt>
            <BNF name="conditional statement"/>
         </alt>
      </rhs>
   </BNFdef>
   <BNFdef name="next statement" predicative="no">
      <rhs>
         <kw>NEXT</kw>
         <opt>
            <BNF name="yield clause"/>
         </opt>
         <BNF name="statement"/>
      </rhs>
   </BNFdef>
   <BNFdef name="graph variable definition" predicative="no">
      <rhs>
         <opt>
            <kw>PROPERTY</kw>
         </opt>
         <kw>GRAPH</kw>
         <BNF name="binding variable"/>
         <BNF name="opt typed graph initializer"/>
      </rhs>
   </BNFdef>
   <BNFdef name="opt typed graph initializer" predicative="no">
      <rhs>
         <opt>
            <opt>
               <BNF name="typed"/>
            </opt>
            <BNF name="graph reference value type"/>
         </opt>
         <BNF name="graph initializer"/>
      </rhs>
   </BNFdef>
   <BNFdef name="graph initializer" predicative="no">
      <rhs>
         <BNF name="equals operator"/>
         <BNF name="graph expression"/>
      </rhs>
   </BNFdef>
   <BNFdef name="binding table variable definition" predicative="no">
      <rhs>
         <opt>
            <kw>BINDING</kw>
         </opt>
         <kw>TABLE</kw>
         <BNF name="binding variable"/>
         <BNF name="opt typed binding table initializer"/>
      </rhs>
   </BNFdef>
   <BNFdef name="opt typed binding table initializer" predicative="no">
      <rhs>
         <opt>
            <opt>
               <BNF name="typed"/>
            </opt>
            <BNF name="binding table reference value type"/>
         </opt>
         <BNF name="binding table initializer"/>
      </rhs>
   </BNFdef>
   <BNFdef name="binding table initializer" predicative="no">
      <rhs>
         <BNF name="equals operator"/>
         <BNF name="binding table expression"/>
      </rhs>
   </BNFdef>
   <BNFdef name="value variable definition" predicative="no">
      <rhs>
         <kw>VALUE</kw>
         <BNF name="binding variable"/>
         <BNF name="opt typed value initializer"/>
      </rhs>
   </BNFdef>
   <BNFdef name="opt typed value initializer" predicative="no">
      <rhs>
         <opt>
            <opt>
               <BNF name="typed"/>
            </opt>
            <BNF name="value type"/>
         </opt>
         <BNF name="value initializer"/>
      </rhs>
   </BNFdef>
   <BNFdef name="value initializer" predicative="no">
      <rhs>
         <BNF name="equals operator"/>
         <BNF name="value expression"/>
      </rhs>
   </BNFdef>
   <BNFdef name="graph expression" predicative="no">
      <rhs>
         <alt>
            <BNF name="object expression primary"/>
         </alt>
         <alt>
            <BNF name="graph reference"/>
         </alt>
         <alt>
            <BNF name="object name or binding variable"/>
         </alt>
         <alt>
            <BNF name="current graph"/>
         </alt>
      </rhs>
   </BNFdef>
   <BNFdef name="current graph" predicative="no">
      <rhs>
         <alt>
            <kw>CURRENT_PROPERTY_GRAPH</kw>
         </alt>
         <alt>
            <kw>CURRENT_GRAPH</kw>
         </alt>
      </rhs>
   </BNFdef>
   <BNFdef name="binding table expression" predicative="no">
      <rhs>
         <alt>
            <BNF name="nested binding table query specification"/>
         </alt>
         <alt>
            <BNF name="object expression primary"/>
         </alt>
         <alt>
            <BNF name="binding table reference"/>
         </alt>
         <alt>
            <BNF name="object name or binding variable"/>
         </alt>
      </rhs>
   </BNFdef>
   <BNFdef name="nested binding table query specification" predicative="no">
      <rhs>
         <BNF name="nested query specification"/>
      </rhs>
   </BNFdef>
   <BNFdef name="object expression primary" predicative="no">
      <rhs>
         <alt>
            <kw>VARIABLE</kw>
            <BNF name="value expression primary"/>
         </alt>
         <alt>
            <BNF name="parenthesized value expression"/>
         </alt>
         <alt>
            <BNF name="non-parenthesized value expression primary special case"/>
         </alt>
      </rhs>
   </BNFdef>
   <BNFdef name="linear catalog-modifying statement" predicative="no">
      <rhs>
         <BNF name="simple catalog-modifying statement"/>
         <repeat/>
      </rhs>
   </BNFdef>
   <BNFdef name="simple catalog-modifying statement" predicative="no">
      <rhs>
         <alt>
            <BNF name="primitive catalog-modifying statement"/>
         </alt>
         <alt>
            <BNF name="call catalog-modifying procedure statement"/>
         </alt>
      </rhs>
   </BNFdef>
   <BNFdef name="primitive catalog-modifying statement" predicative="no">
      <rhs>
         <alt>
            <BNF name="create schema statement"/>
         </alt>
         <alt>
            <BNF name="drop schema statement"/>
         </alt>
         <alt>
            <BNF name="create graph statement"/>
         </alt>
         <alt>
            <BNF name="drop graph statement"/>
         </alt>
         <alt>
            <BNF name="create graph type statement"/>
         </alt>
         <alt>
            <BNF name="drop graph type statement"/>
         </alt>
         <alt>
            <BNF name="create constraint statement"/>
         </alt>
         <alt>
            <BNF name="drop constraint statement"/>
         </alt>
      </rhs>
   </BNFdef>
   <BNFdef name="create schema statement" predicative="no">
      <rhs>
         <kw>CREATE</kw>
         <kw>SCHEMA</kw>
         <opt>
            <kw>IF</kw>
            <kw>NOT</kw>
            <kw>EXISTS</kw>
         </opt>
         <BNF name="catalog schema parent and name"/>
      </rhs>
   </BNFdef>
   <BNFdef name="drop schema statement" predicative="no">
      <rhs>
         <kw>DROP</kw>
         <kw>SCHEMA</kw>
         <opt>
            <kw>IF</kw>
            <kw>EXISTS</kw>
         </opt>
         <BNF name="catalog schema parent and name"/>
      </rhs>
   </BNFdef>
   <BNFdef name="create graph statement" predicative="no">
      <rhs>
         <kw>CREATE</kw>
         <group>
            <alt>
               <opt>
                  <kw>PROPERTY</kw>
               </opt>
               <kw>GRAPH</kw>
               <opt>
                  <kw>IF</kw>
                  <kw>NOT</kw>
                  <kw>EXISTS</kw>
               </opt>
            </alt>
            <alt>
               <kw>OR</kw>
               <kw>REPLACE</kw>
               <opt>
                  <kw>PROPERTY</kw>
               </opt>
               <kw>GRAPH</kw>
            </alt>
         </group>
         <BNF name="catalog graph parent and name"/>
         <group>
            <alt>
               <BNF name="open graph type"/>
            </alt>
            <alt>
               <BNF name="of graph type"/>
            </alt>
         </group>
         <opt>
            <BNF name="graph source"/>
         </opt>
      </rhs>
   </BNFdef>
   <BNFdef name="open graph type" predicative="no">
      <rhs>
         <opt>
            <BNF name="typed"/>
         </opt>
         <kw>ANY</kw>
         <opt>
            <opt>
               <kw>PROPERTY</kw>
            </opt>
            <kw>GRAPH</kw>
         </opt>
      </rhs>
   </BNFdef>
   <BNFdef name="of graph type" predicative="no">
      <rhs>
         <alt>
            <BNF name="graph type like graph"/>
         </alt>
         <alt>
            <opt>
               <BNF name="typed"/>
            </opt>
            <BNF name="graph type reference"/>
         </alt>
         <alt>
            <opt>
               <BNF name="typed"/>
            </opt>
            <opt>
               <opt>
                  <kw>PROPERTY</kw>
               </opt>
               <kw>GRAPH</kw>
            </opt>
            <BNF name="nested graph type specification"/>
         </alt>
      </rhs>
   </BNFdef>
   <BNFdef name="graph type like graph" predicative="no">
      <rhs>
         <kw>LIKE</kw>
         <BNF name="graph expression"/>
      </rhs>
   </BNFdef>
   <BNFdef name="graph source" predicative="no">
      <rhs>
         <kw>AS</kw>
         <kw>COPY</kw>
         <kw>OF</kw>
         <BNF name="graph expression"/>
      </rhs>
   </BNFdef>
   <BNFdef name="drop graph statement" predicative="no">
      <rhs>
         <kw>DROP</kw>
         <opt>
            <kw>PROPERTY</kw>
         </opt>
         <kw>GRAPH</kw>
         <opt>
            <kw>IF</kw>
            <kw>EXISTS</kw>
         </opt>
         <BNF name="catalog graph parent and name"/>
      </rhs>
   </BNFdef>
   <BNFdef name="create graph type statement" predicative="no">
      <rhs>
         <kw>CREATE</kw>
         <group>
            <alt>
               <opt>
                  <kw>PROPERTY</kw>
               </opt>
               <kw>GRAPH</kw>
               <kw>TYPE</kw>
               <opt>
                  <kw>IF</kw>
                  <kw>NOT</kw>
                  <kw>EXISTS</kw>
               </opt>
            </alt>
            <alt>
               <kw>OR</kw>
               <kw>REPLACE</kw>
               <opt>
                  <kw>PROPERTY</kw>
               </opt>
               <kw>GRAPH</kw>
               <kw>TYPE</kw>
            </alt>
         </group>
         <BNF name="catalog graph type parent and name"/>
         <BNF name="graph type source"/>
      </rhs>
   </BNFdef>
   <BNFdef name="graph type source" predicative="no">
      <rhs>
         <alt>
            <opt>
               <kw>AS</kw>
            </opt>
            <BNF name="copy of graph type"/>
         </alt>
         <alt>
            <BNF name="graph type like graph"/>
         </alt>
         <alt>
            <opt>
               <kw>AS</kw>
            </opt>
            <BNF name="nested graph type specification"/>
         </alt>
      </rhs>
   </BNFdef>
   <BNFdef name="copy of graph type" predicative="no">
      <rhs>
         <kw>COPY</kw>
         <kw>OF</kw>
         <group>
            <alt>
               <BNF name="graph type reference"/>
            </alt>
            <alt>
               <BNF name="external object reference"/>
            </alt>
         </group>
      </rhs>
   </BNFdef>
   <BNFdef name="drop graph type statement" predicative="no">
      <rhs>
         <kw>DROP</kw>
         <opt>
            <kw>PROPERTY</kw>
         </opt>
         <kw>GRAPH</kw>
         <kw>TYPE</kw>
         <opt>
            <kw>IF</kw>
            <kw>EXISTS</kw>
         </opt>
         <BNF name="catalog graph type parent and name"/>
      </rhs>
   </BNFdef>
   <BNFdef name="call catalog-modifying procedure statement" predicative="no">
      <rhs>
         <BNF name="call procedure statement"/>
      </rhs>
   </BNFdef>
   <BNFdef name="create constraint statement" predicative="no">
      <rhs>
         <kw>CREATE</kw>
         <group>
            <alt>
               <kw>CONSTRAINT</kw>
               <opt>
                  <kw>IF</kw>
                  <kw>NOT</kw>
                  <kw>EXISTS</kw>
               </opt>
            </alt>
            <alt>
               <kw>OR</kw>
               <kw>REPLACE</kw>
               <kw>CONSTRAINT</kw>
            </alt>
         </group>
         <opt>
            <BNF name="constraint parent graph specification"/>
         </opt>
         <BNF name="constraint specification"/>
      </rhs>
   </BNFdef>
   <BNFdef name="constraint parent graph specification" predicative="no">
      <rhs>
         <BNF name="graph expression"/>
         <BNF name="period"/>
      </rhs>
   </BNFdef>
   <BNFdef name="drop constraint statement" predicative="no">
      <rhs>
         <kw>DROP</kw>
         <kw>CONSTRAINT</kw>
         <opt>
            <kw>IF</kw>
            <kw>EXISTS</kw>
         </opt>
         <opt>
            <BNF name="constraint parent graph specification"/>
         </opt>
         <BNF name="constraint name"/>
      </rhs>
   </BNFdef>
   <BNFdef name="linear data-modifying statement" predicative="no">
      <rhs>
         <alt>
            <BNF name="focused linear data-modifying statement"/>
         </alt>
         <alt>
            <BNF name="ambient linear data-modifying statement"/>
         </alt>
      </rhs>
   </BNFdef>
   <BNFdef name="focused linear data-modifying statement" predicative="no">
      <rhs>
         <alt>
            <BNF name="focused linear data-modifying statement body"/>
         </alt>
         <alt>
            <BNF name="focused nested data-modifying procedure specification"/>
         </alt>
      </rhs>
   </BNFdef>
   <BNFdef name="focused linear data-modifying statement body" predicative="no">
      <rhs>
         <BNF name="use graph clause"/>
         <BNF name="simple linear data-accessing statement"/>
         <opt>
            <BNF name="primitive result statement"/>
         </opt>
      </rhs>
   </BNFdef>
   <BNFdef name="focused nested data-modifying procedure specification"
            predicative="no">
      <rhs>
         <BNF name="use graph clause"/>
         <BNF name="nested data-modifying procedure specification"/>
      </rhs>
   </BNFdef>
   <BNFdef name="ambient linear data-modifying statement" predicative="no">
      <rhs>
         <alt>
            <BNF name="ambient linear data-modifying statement body"/>
         </alt>
         <alt>
            <BNF name="nested data-modifying procedure specification"/>
         </alt>
      </rhs>
   </BNFdef>